spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/chwimeet?currentSchema=chwimeet
    username: root
    password: ${SPRING__DATASOURCE__PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  ai:
    vectorstore:
      mariadb:
        initialize-schema: true
        schema-validation: false
        schema-name: chwimeet
        table-name: vector_store
        dimensions: 1536
        distance-type: COSINE
