spring:
  datasource:
    url: ${SPRING__DATASOURCE__URL}
    username: ${SPRING__DATASOURCE__USERNAME}
    password: ${SPRING__DATASOURCE__PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        use_sql_comments: false

  ai:
    vectorstore:
      mariadb:
        initialize-schema: true
        schema-validation: false
        schema-name: chwimeet
        table-name: vector_store
        dimensions: 1536
        distance-type: COSINE

logging:
  level:
    com.back: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG